13/09/2021 19:42:50 - root - INFO - ----------START----------

13/09/2021 19:42:50 - root - INFO - New date are avalable: False
13/09/2021 19:42:50 - root - INFO - Connection with proxy: proxy.voip.plus:8080
13/09/2021 19:42:50 - root - INFO - Check connection
13/09/2021 19:42:50 - root - INFO - While loop, host: ('proxy.voip.plus', 8080)
13/09/2021 19:42:50 - root - INFO - checked
13/09/2021 19:42:50 - root - INFO - Port is closed
13/09/2021 19:42:50 - root - INFO - Knocking
13/09/2021 19:42:50 - root - INFO - Knocking to port: proxy.voip.plus: 15236
13/09/2021 19:42:51 - root - INFO - Knocking to port: proxy.voip.plus: 12236
13/09/2021 19:42:51 - root - INFO - Check connection
13/09/2021 19:42:51 - root - INFO - While loop, host: ('proxy.voip.plus', 8080)
13/09/2021 19:42:51 - root - INFO - checked
13/09/2021 19:42:51 - root - INFO - Port is open
13/09/2021 19:42:51 - root - INFO - Proxy connected Succesfully

13/09/2021 19:42:51 - root - INFO - Connecting with Proxy: proxy.voip.plus:8080
13/09/2021 19:42:52 - root - INFO - Registration are started

13/09/2021 19:42:52 - root - INFO - Enter Login page
13/09/2021 19:42:57 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /session/412c55ba68dc9dc9a0c65e7106ef6a22
13/09/2021 19:42:57 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8402b21160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/412c55ba68dc9dc9a0c65e7106ef6a22
13/09/2021 19:42:57 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8402b212b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/412c55ba68dc9dc9a0c65e7106ef6a22
